### PR TITLE
Fixes for PHP 8.1

### PR DESCRIPTION
**Pull request by cweiske**
The tests pass in a docker container with PHP 7.4, 8.0, 8.1 and 8.2.

@hbeni please review + merge.

### CODE REVIEW

**Comment by Neustradamus** [comment]
@hbeni: Have you seen the @cweiske PR?

**Review by CloCkWeRX — APPROVED** [review]
That all seems sensible.

**Comment by cweiske** [comment]
Released as v2.3.0

**Comment by Neustradamus** [comment]
@cweiske: Thanks for merging!
Do not forget to create the release here (in more the tag):
- https://github.com/pear/Net_LDAP2/releases

**Comment by cweiske** [comment]
Why is a tag not enough?

**Comment by Neustradamus** [comment]
@cweiske: At right on https://github.com/pear/Net_LDAP2/pull/13
Releases 1
v2.2.1 (Latest)
on Feb 8

**Comment by Neustradamus** [comment]
@cweiske: At right on https://github.com/pear/Net_LDAP2/
Releases 1
v2.2.1 (Latest)
on Feb 8

**Comment by cweiske** [comment]
I know that there is one release already.
But I ask again: Why is a tag not enough? What does the release give us in addition?

**Comment by colisee** [comment]
Hi @cweiske ,

Together with @effgarces, I am participating to the repository librebooking/app and I realized that our librebooking sources contained an old copy of Net_LDAP2. 

I wish to remove the old Net_LDAP2 sources and use instead Net_LDAP2 through the PEAR application repositories. In such case, wouldn't you need to add a new release in order to include the latest fix into PEAR?

Thanks.

**Comment by cweiske** [comment]
Yes, this would be necessary. But a release on pear.php.net is different from a release on github.
I also won't do a release on pear.php.net. If others have the time and will to do that - please go on.

**Comment by colisee** [comment]
OK: got it

I saw that the pear Net_LDAP2 repository is no longer maintained. I will check if it is worthwhile for me to takeover the lead on that pear repository for the benefit of our librebooking project.

**Comment by Neustradamus** [comment]
@colisee: Good catch, pear.php.net is not updated when a version is released on GitHub!
- https://pear.php.net/package/net_ldap2

**Pull request merged**
